'use client'

import Link from 'next/link'
import { motion } from 'framer-motion'
import { ArrowUpRight, Bot, Code2, LayoutTemplate, Megaphone, RefreshCw, Search, ShoppingBag, Sparkles, Wrench } from 'lucide-react'
import { ServicesMarquee } from '@/components/sections/ServicesMarquee'

const services = [{ icon: Code2, title: 'Web development', text: 'High-performance websites and web apps with a foundation built to scale.', tag: 'Build' }, { icon: RefreshCw, title: 'Website redesign', text: 'A clearer, faster digital presence that respects what already works.', tag: 'Refresh' }, { icon: LayoutTemplate, title: 'Landing pages', text: 'Focused pages for launches, offers, and campaigns that need traction.', tag: 'Convert' }, { icon: Bot, title: 'AI & chatbot integration', text: 'Practical AI systems that answer, qualify, and automate without losing the human touch.', tag: 'Automate' }, { icon: Search, title: 'SEO websites', text: 'Technical foundations and content structures that help the right people find you.', tag: 'Be found' }, { icon: Megaphone, title: 'Google, Meta & ChatGPT ads', text: 'Performance campaigns connected to strong creative and a measurable next step.', tag: 'Grow' }, { icon: ShoppingBag, title: 'Ecommerce', text: 'Online stores that make browsing, buying, and managing orders feel simple.', tag: 'Sell' }, { icon: Wrench, title: 'Support & maintenance', text: 'Ongoing care, improvements, and technical calm after launch.', tag: 'Keep going' }]

export default function ServicesPage() { return <main><ServicesMarquee /><section className="relative px-6 pb-24 pt-24 sm:px-10 lg:px-16 lg:pb-32 lg:pt-36"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_20%_20%,rgba(84,172,191,0.2),transparent_28%)]" /><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#a7ebf2]">Capabilities</p><div className="mt-8 flex flex-col justify-between gap-10 lg:flex-row lg:items-end"><h1 className="max-w-4xl text-5xl font-semibold leading-[.98] tracking-[-.04em] text-white sm:text-7xl">The right digital <span className="text-[#a7ebf2]">move.</span></h1><p className="max-w-md text-lg leading-8 text-[#b5d4dc]">Choose the piece you need, or bring us the whole puzzle. We connect strategy, design, technology, and distribution.</p></div></div></section><section className="bg-[#edfaff] px-6 py-20 text-[#011c2d] sm:px-10 lg:px-16 lg:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-px overflow-hidden rounded-3xl border border-[#54acbf]/25 bg-[#54acbf]/25 md:grid-cols-2 lg:grid-cols-4">{services.map(({ icon: Icon, title, text, tag }, index) => <motion.article key={title} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .05 }} className="group flex min-h-80 flex-col bg-[#edfaff] p-7 transition hover:bg-white"><div className="flex items-center justify-between text-[#26658c]"><Icon size={26} /><span className="text-xs font-bold uppercase tracking-[.15em]">{tag}</span></div><h2 className="mt-auto text-2xl font-bold">{title}</h2><p className="mt-4 leading-7 text-[#26658c]">{text}</p><Link href="/contact" className="mt-6 flex items-center gap-2 text-sm font-bold text-[#0d5c73]">Discuss this <ArrowUpRight size={16} /></Link></motion.article>)}</div></div></section><section className="px-6 py-24 sm:px-10 lg:px-16 lg:py-32"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 rounded-[2rem] border border-[#a7ebf2]/20 bg-[#082f49] p-8 sm:p-12 lg:flex-row lg:items-end"><div><Sparkles className="text-[#a7ebf2]" size={28} /><h2 className="mt-8 max-w-2xl text-4xl font-semibold leading-tight text-white sm:text-5xl">Not sure where to start? That is exactly where discovery helps.</h2></div><Link href="/contact" className="inline-flex shrink-0 items-center gap-2 rounded-full bg-[#a7ebf2] px-6 py-3 font-bold text-[#011c2d] transition hover:bg-white">Book a discovery call <ArrowUpRight size={17} /></Link></div></section></main> }
